version: '3.3'

services:
  web:
    container_name: tz_pg_web
    restart: always
    build:
      context: ./
      dockerfile: _docker/Dockerfile
    command: bash -c "uvicorn src.app:app --port 8000 --host 0.0.0.0"
    volumes:
      - ./:/home/tz_pg
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
